name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: baixar o projeto
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mostrar arquivos do projeto
        run: ls -la

      - name: Analisar código com SonarCloud
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy para S3
        run: |
          aws s3 sync . s3://teste-devops-ivory-site --delete
